name: Deploy Node.js to Azure Web App

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: "solara"
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "20.12.2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build project
        run: npm run build --if-present

      - name: Verify build output
        run: |
          [ -f dist/index.js ] || echo "##[error] Missing dist/index.js"
          ls -la dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Web App
        run: |
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group Decentralize_group \
            --startup-file "npm start" \
            --linux-fx-version "NODE|20-lts"

          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group Decentralize_group \
            --settings \
              WEBSITES_PORT=8080 \
              NODE_ENV=production \
              DATABASE_URL=${{ secrets.DATABASE_URL }} \
              PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
              EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} \
              EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
          slot-name: production